add Book model, repository and service
MurphyEdward/Online-Book-Store pull request #1
Opened 2024-02-25 16:41 UTC by MurphyEdward

2024-02-25 18:55 UTC, okuzan requested changes

2024-02-25 18:55 UTC, okuzan commented on .github/workflows/ci.yml
> +        run: mvn --batch-mode --update-snapshots verify
```suggestion
        run: mvn --batch-mode --update-snapshots verify

```

2024-02-25 18:55 UTC, okuzan commented on checkstyle.xml
> +</module>
```suggestion
</module>

```

2024-02-25 18:55 UTC, okuzan commented on src/main/java/com/github/onlinebookstore/repositories/impl/BookRepositoryImpl.java
> +        return null;
add implementation

2024-02-25 18:55 UTC, okuzan commented on src/main/java/com/github/onlinebookstore/services/impl/BookServiceImpl.java
> +        return null;
add implementation

2024-02-25 18:55 UTC, okuzan commented on src/main/java/com/github/onlinebookstore/OnlineBookStoreApplication.java
> +
```suggestion
```

2024-02-26 15:15 UTC, olekskov approved these changes

2024-03-05 18:00 UTC, merged