Add tests
MurphyEdward/Online-Book-Store pull request #15
Opened 2024-07-10 10:44 UTC by hlibmurphy

2024-07-10 10:50 UTC, hlibmurphy commented
![image](https://github.com/hlibmurphy/Online-Bookstore/assets/32224665/68150ab8-89e9-471c-9890-e5a2f5cb17eb)

2024-07-11 10:23 UTC, MentorMateAcademy requested changes
You have changes not related with this task

2024-07-11 10:23 UTC, MentorMateAcademy commented on .env.template
> +JWT_EXPIRATION=300000
why you add this changes in this pr?

2024-07-11 18:26 UTC, okuzan approved these changes

2024-07-15 17:27 UTC, merged