add and implement dto and controller; update book repository and service
MurphyEdward/Online-Book-Store pull request #2
Opened 2024-03-05 22:00 UTC by MurphyEdward

2024-03-06 12:45 UTC, okuzan requested changes
minor fixes

2024-03-06 12:45 UTC, okuzan commented on src/main/java/com/github/onlinebookstore/controller/BookController.java
> +@RequestMapping("/api")
extract api to properties - server servlet context-path

2024-03-06 12:45 UTC, okuzan commented on src/main/java/com/github/onlinebookstore/model/Book.java
> +    //@JsonProperty(access = JsonProperty.Access.READ_ONLY)
don't forget to remove commented out code

2024-03-07 11:56 UTC, kozhukhovsky approved these changes

2024-03-11 23:22 UTC, merged