implement login using jwt token
MurphyEdward/Online-Book-Store pull request #9
Opened 2024-04-17 10:09 UTC by MurphyEdward

2024-04-17 17:14 UTC, kerrrusha requested changes
almost perfect

2024-04-17 17:14 UTC, kerrrusha commented on src/main/java/com/github/onlinebookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
please make this strings as constants
```suggestion
        String bearerToken = request.getHeader(AUTH_HEADER);
        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(TOKEN_START)) {
```

2024-04-17 17:14 UTC, kerrrusha commented on src/main/java/com/github/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(TOKEN_START.length());
```

2024-04-18 09:08 UTC, kozhukhovsky approved these changes

2024-04-21 15:54 UTC, closed without merging